"use client";
import { Layout, Breadcrumb, Menu, MenuProps } from "antd";
const { Header, Sider, Content, Footer } = Layout;
export const AntdLayout = Layout;
export const AntdBreadcrumb = Breadcrumb;
export const AntdHeader = Header;
export const AntdSider = Sider;
export const AntdContent = Content;
export const AntdFooter = Footer;
export const AntdMenu = Menu;
